name: Publish Gallery
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Publish Gallery to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker run -t -i -v "$(pwd):/work" thumbsupgallery/thumbsup /bin/sh -c "cd /work/ && thumbsup --config config.json"